server:
  port: 8002
spring:
  application:
    name: api-gateway

  zipkin:
      base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost


zuul:
  ignoredServices: '*'
  routes:
    order-service:
      path: /order/**
      serviceId: order-service
      stripPrefix: true
    product-service:
      path: /product/**
      serviceId: product-service
      stripPrefix: true
    customer-service:
      path: /customer/**
      serviceId: customer-service
      stripPrefix: true
    cart-command-service:
      path: /cart-command/**
      serviceId: shopping-cart-command-service
      stripPrefix: true
    cart-query-service:
      path: /cart-query/**
      serviceId: shopping-cart-query-service
      stripPrefix: true

ribbon:
  ReadTimeout=10000:
