server.port: 8010

spring:
  application:
    name: customer-service

  data.mongodb:
    host: localhost
    port: 27010
    database: customer
    authentication-database: admin
    username: root
    password: testd

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/